### ISSUE TITLE
Upload drag and drop - Showing additional blue drop area

### ISSUE THREAD

**Issue by louisl** [svenbolte/delightful-downloads#1]
Hello, thanks for making this fork.

I have an issue when uploading.

When dragging and dropping over the upload area an additional blue drop area appears.

Dropping in the white area uploads to the delightful-downloads folder and allocates the file to downloads.

Dropping in the blue area uploads to the WP Media Library and **does not allocate** the file to downloads.

![upload-problems](https://user-images.githubusercontent.com/1140394/104003685-a4679f80-519a-11eb-9177-7ccce7cfa1ff.jpg)

**Comment by svenbolte** [comment]
the blue area is a feature of wordpress editor as you can add attachments to post content via drag and drop. 
I sometime use it to add an image to the content cos i enabled the archives and use downloads as regular posts.

Did not find a way to make the ddl drag and drop box (the white one) resized to full screen (which would resolve your issue) :(

**Comment by svenbolte** [comment]
managed to place the drag box für downloads on bottom of the page. you will still see the blue box of the editor as grey box, but when you drag on the dedo upload drop area it will add your drop as a download. Just get Version 9.9.33

**Comment by svenbolte** [comment]
fixed with 9.9.33 so blue editor dropzone and dedo dropzone will work now

**Comment by louisl** [comment]
Thanks, will take a look as soon as I get a chance.
