### ISSUE TITLE
fontawesome - Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by medentis** [svenbolte/delightful-downloads#10]
I get the following error in the browser console. GET https://medentis.com/wp-content/plugins/delightful-downloads/includes/assets/fontawesomeplus.min.css?ver=6.6.1 net::ERR_ABORTED 404 (Not Found)

<img width="537" alt="Bildschirmfoto 2024-08-28 um 09 55 00" src="https://github.com/user-attachments/assets/9f741194-c5b1-46ef-9d85-c438be21354b">

Best regards
Stefan

**Comment by svenbolte** [comment]
Thanks for the hint. the path is fixed now.

**Comment by svenbolte** [comment]
path fixed
