### ISSUE TITLE
Feature Request, limit number of downloads by logged in user per day

### ISSUE THREAD

**Issue by EddiebNZ** [svenbolte/delightful-downloads#2]
Any chance of adding the ability to specify a maximum number of downloads a logged in user can make per day?

**Comment by svenbolte** [comment]
I do not use the feature with user downloads cos i dont have registered users on my site.  thats why i dont have a focus on it.

But you can send a user a one-day-ticket valid today or tomorrow (it is offered in the dls list in admin area). this wont prevent the user giving the ticket to someone else but it is limited in time.
