### ISSUE TITLE
[Question] - Download logs date

### ISSUE THREAD

**Issue by louisl** [svenbolte/delightful-downloads#3]
In the download logs date I see things like:

```
vor 47 mins
16 September 2021 at 7:28 pm
```

I assume that's German and translates to 

```
Before 47 mins
16 September 2021 at 7:28 pm
```

But what is the context of 'vor/before 47 mins'? What does it actually mean?

**Comment by svenbolte** [comment]
yup. I apparently put a german word in the code. Will replace it by __( function and wight text domain.
it is the human timediff between download date in the list and now

**Comment by svenbolte** [comment]
this should be fixed and improved now. if youre using a theme with font awesome 4.7 font you can see some icons for date/download size and similar things too. translations should be origin in english now
