### ISSUE TITLE
Delightful Downloads still alive?

### ISSUE THREAD

**Issue by mircobabini** [svenbolte/delightful-downloads#5]
Hey @svenbolte and @A5hleyRich.

Why not working together to provide an official home to this Delightful Downloads updated codebase?

**Comment by svenbolte** [comment]
Hi Mirco,
i do not have any contact to Ashley. When i noticed the death of dedo in wp plugins list, i created my fork to remove the security breach and add new features and adjust to php8 and current wp versions...

I keep development up on github cos i do not like the repository on wp.

**Comment by svenbolte** [comment]
i will continue further development of the plugin here
