### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by obewanz** [svenbolte/delightful-downloads#6]
You know what really pisses me off?? People who CLOSE SUPPORT TICKETS without getting a verification that the issue has been resolved.

THIS ISSUE IS NOT RESOLVED!!!

Inside the readme.txt file: 
`"Please refer to the [documentation](https://delightfuldownloads.com/documentation/installation/ "Delightful Downloads Documentation") for further instructions."`

![image](https://user-images.githubusercontent.com/19472964/194561010-6f841fe6-5b3c-495a-a18d-999a497c7deb.png)
As you can see in the image of the directory structure within the zip file - the "/documentation/installation/" folder DOES NOT EXIST!

It's not even in the repository either:
![image](https://user-images.githubusercontent.com/19472964/194561226-c0846676-c0ea-4e8b-af44-3c52cb88c9a6.png)

And just so you know, the new updated readme.txt in the repository pointing to documentation-styles.pdf is incorrect as well - that file isn't in the repository either!

![Screenshot_3](https://user-images.githubusercontent.com/19472964/194562815-ce115740-26a9-42e1-a30b-85390f9abf1f.jpg)

Please do NOT close this issue again until you have VERIFIED that it has been resolved!
Thanks!

**Comment by svenbolte** [comment]
thank you for the hint. i moved the documentation to the readme file but did not give a hint in readme.md and readme.txt. 
You can find the detailed documentation and faq in the readme file of the plugin.
As issue is now fixed i close it.
