### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by lfriedman74** [svenbolte/delightful-downloads#8]
Hello,

First, thanks for forking and maintaining this plugin. Question: The main URL for my downloads is showing up as /dedo_download/[download_name]. That URL leads to a page that looks like the attached. 
![image](https://github.com/svenbolte/delightful-downloads/assets/6518394/8e13b183-cf9c-4a58-9386-4185745fe1d8)

Instead of directing to the page which doesn't have a download link, is there a way to directly open the download in the browser? I don't have the opportunity to copy and paste the shortcode in a dynamic template.

I have read the docs and tried different settings but nothing seems to make a difference.

Thanks,
Lou

**Comment by svenbolte** [comment]
the single page of the downloads which is invoked when clicking on the symbol in lists DOES have a download button, as you can see on the screenshot. Clicking on the title in lists or when embedding a shortcode leads to https://site.com/?ddownload=3071
![Screenshot 2024-08-24 135337](https://github.com/user-attachments/assets/aab0acef-0106-4695-b885-c8215032d598)

**Comment by svenbolte** [comment]
Update: .82 i added a silver background on direct download button and a border. in my theme/template i use theme accent color for buttons. Now you should see the direct download button too.

**Comment by svenbolte** [comment]
download button now visible on all themes
