### ISSUE TITLE
buggy custom javascript code that removes and overwrites the default global WordPress javascript variables 

### ISSUE THREAD

**Issue by medentis** [svenbolte/delightful-downloads#9]
Dear Sven,

first of all, thank you for the further development of the plugin.
Unfortunately I have a problem with the otherwise great plugin.

We are using the theme from https://essentials.pixfort.com/
Unfortunately, the Delightful Downloads plugin contains buggy custom javascript code that removes and overwrites the default global WordPress javascript variables to replace them with custom data in the plugin's javascript code. As a result, the theme unfortunately only works to a very limited extent, as some control panels cannot be opened.
Here is a picture of the code.

I would be very grateful if you could correct the code.

Best regards
Stefan

![image](https://github.com/svenbolte/delightful-downloads/assets/134295474/6c9739f8-e790-4391-b068-ec51f2924b41)
<img width="1184" alt="Bildschirmfoto 2024-07-02 um 10 37 00" src="https://github.com/svenbolte/delightful-downloads/assets/134295474/f5b0f58b-cc7f-4a5e-be7c-21b72ba253bc">

**Comment by medentis** [comment]
something else. how is it possible to open a new tab when clicking on a download?

**Comment by svenbolte** [comment]
Hi Stefan,

the jquery part was taken from the master branch. As im not familiar with javascript, please provide a change how to fix this.

**Comment by svenbolte** [comment]
I let JS and css thru a web optimization and new minifier. minified code looks different now, maybe it helps. if not i will need how to replace self thing.

opening a new page when clicking on a link is not possible without adding your own template

**Comment by svenbolte** [comment]
i close this issue due to no further responds
